services:
  - type: web
    name: cothu-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: singapore
    plan: free
    healthCheckPath: /api/game/list
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
